apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-fuck-dep
  labels:
    app: e-store-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-fucker
  template:
    metadata:
      labels:
        app: cpu-fucker
    spec:
      containers:
        - name: cpu-fucker
          image: darshanasamanpura/cputest:v5
          ports:
            - containerPort: 8080
              name: service-port
          resources:
            requests:
              cpu: "250m"
#          hostPort: 8080



---
apiVersion: v1
kind: Service
metadata:
  name: cpu-fucker-network-service
spec:
  type: LoadBalancer
  selector:
    app: cpu-fucker
  ports:
    - name: rest-port
      protocol: TCP
      targetPort: 8080
      port: 80
      #nodePort: 32500

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cpu-fucker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cpu-fuck-dep
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50



